import { HistoryItem, SampleLeaf, SensorData } from './types';

export const DEFAULT_SENSOR_DATA: SensorData = {
  soilMoisture: 42,
  temperature: 24,
  humidity: 68,
  isWatering: false,
  lastWateredTime: '2 hours ago',
  lastWateredTimeHi: '2 घंटे पहले',
  rainExpected: true,
  cropHealthStatus: 'healthy',
  cropHealthLabel: 'Healthy',
  cropHealthLabelHi: 'स्वस्थ',
  cropHealthSubtitle: 'All vitals nominal',
  cropHealthSubtitleHi: 'सभी महत्वपूर्ण अंग सामान्य हैं',
};

export const SAMPLE_LEAVES: SampleLeaf[] = [
  {
    id: 'sample-early-blight',
    name: 'Tomato Leaf (Blighted)',
    nameHi: 'टमाटर की पत्ती (झुलसा रोग)',
    crop: 'Tomato',
    cropHi: 'टमाटर',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBwKZLTI0w9B2xeIQOCYcqrKDMzqT5IlvzA6pgXsj-hAtP7cuIqpgekY0RfvSh-cwp6tD_lDCPHCjsnWK-2hX5I9WSxTBx9UZEcLgWwa57xtQJRzADyW_tV6IjB56-fUIelm5UypFxct3rJqipyGbFkTGDmjkDJYtmtVmLKbsN5QYCvRHpYMpuPH9pobHBs4ps6zGNyEgK3aU-F8fKiqJ3HQnI1c_2ZpwJet-9WUA-VsLgB7RXP_P8',
    expectedDiagnosis: 'Early Blight',
    expectedDiagnosisHi: 'अर्ली ब्लाइट (अगेती झुलसा)',
    isHealthy: false,
    confidence: 85,
    advisory: 'Apply a copper-based fungicide immediately. Ensure adequate spacing between plants to improve air circulation. Remove and destroy severely infected lower leaves to prevent spread to the upper canopy. Monitor moisture levels carefully.',
    advisoryHi: 'तुरंत तांबा आधारित कवकनाशी (कॉपर फंगीसाइड) का छिड़काव करें। हवा के प्रवाह को बेहतर बनाने के लिए पौधों के बीच पर्याप्त दूरी रखें। ऊपरी पत्तों में फैलाव रोकने के लिए गंभीर रूप से संक्रमित निचले पत्तों को काटकर नष्ट कर दें। मिट्टी और हवा की नमी पर सावधानीपूर्वक नज़र रखें।',
  },
  {
    id: 'sample-healthy-corn',
    name: 'Corn Leaf (Healthy)',
    nameHi: 'मक्के की पत्ती (स्वस्थ)',
    crop: 'Corn / Maize',
    cropHi: 'मक्का',
    imageUrl: 'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=800&q=80',
    expectedDiagnosis: 'Healthy Foliage',
    expectedDiagnosisHi: 'स्वस्थ पत्तियां',
    isHealthy: true,
    confidence: 96,
    advisory: 'Crop vitals and leaf tissue are vigorous and free of pest or fungal lesions. Continue scheduled balanced nitrogen-phosphorus irrigation cycle.',
    advisoryHi: 'फसल की पत्तियां पूरी तरह स्वस्थ और हरी-भरी हैं। कोई कीट या फफूंद के लक्षण नहीं मिले हैं। निर्धारित समय पर संतुलित खाद व पानी जारी रखें।',
  },
  {
    id: 'sample-potato-blight',
    name: 'Potato Leaf (Late Blight)',
    nameHi: 'आलू की पत्ती (पछेती झुलसा)',
    crop: 'Potato',
    cropHi: 'आलू',
    imageUrl: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&w=800&q=80',
    expectedDiagnosis: 'Late Blight (Phytophthora)',
    expectedDiagnosisHi: 'पछेती झुलसा (लेट ब्लाइट)',
    isHealthy: false,
    confidence: 89,
    advisory: 'High risk fungal alert! Spray systemic fungicides such as Metalaxyl or Mancozeb immediately. Avoid overhead sprinkler irrigation during humid mornings.',
    advisoryHi: 'गंभीर फफूंद चेतावनी! तुरंत मेटालैक्सिल या मैंकोजेब कवकनाशी का छिड़काव करें। सुबह के समय फव्वारा सिंचाई से बचें ताकि पत्तियां सूखी रहें।',
  },
];

export const INITIAL_HISTORY: HistoryItem[] = [
  {
    id: 'h-1',
    title: 'Watered Field A',
    titleHi: 'खेत A में सिंचाई',
    category: 'irrigation',
    subtitle: '30s duration • Sector 4',
    subtitleHi: '30 सेकंड अवधि • सेक्टर 4',
    time: '10:45 AM',
    dateGroup: 'today',
    icon: 'water_drop',
    iconBgClass: 'bg-[#1b4332] text-[#86af99]',
    iconColorClass: 'text-[#86af99]',
    trendText: 'Moisture +12%',
    trendTextHi: 'नमी +12%',
    trendIcon: 'trending_up',
    trendType: 'positive',
  },
  {
    id: 'h-2',
    title: 'Disease Check',
    titleHi: 'रोग की जाँच',
    category: 'disease_check',
    subtitle: 'Corn leaves • Result: Healthy',
    subtitleHi: 'मक्के के पत्ते • परिणाम: स्वस्थ',
    time: '08:15 AM',
    dateGroup: 'today',
    icon: 'photo_camera',
    iconBgClass: 'bg-[#3d3c2f] text-[#a8a695]',
    iconColorClass: 'text-[#a8a695]',
  },
  {
    id: 'h-3',
    title: 'Heat Alert',
    titleHi: 'अत्यधिक तापमान चेतावनी',
    category: 'alert',
    subtitle: 'Temperature exceeded 35°C',
    subtitleHi: 'तापमान 35°C से अधिक हुआ',
    time: '02:30 PM',
    dateGroup: 'yesterday',
    icon: 'thermostat',
    iconBgClass: 'bg-[#ffdad6] text-[#ba1a1a]',
    iconColorClass: 'text-[#ba1a1a]',
    trendText: 'Moisture -5%',
    trendTextHi: 'नमी -5%',
    trendIcon: 'trending_down',
    trendType: 'negative',
  },
  {
    id: 'h-4',
    title: 'Tractor Deployed',
    titleHi: 'ट्रैक्टर कार्य',
    category: 'operation',
    subtitle: 'Field B • Soil tilling',
    subtitleHi: 'खेत B • मिट्टी की जुताई',
    time: '09:00 AM',
    dateGroup: 'yesterday',
    icon: 'agriculture',
    iconBgClass: 'bg-[#ffca98] text-[#7a532a]',
    iconColorClass: 'text-[#7a532a]',
  },
];

export const TRANSLATIONS = {
  en: {
    appName: 'Harvex',
    dashboard: 'Dashboard',
    leafCheck: 'Leaf Check',
    history: 'History',
    cropHealth: 'Crop Health',
    healthy: 'Healthy',
    allVitalsNominal: 'All vitals nominal',
    irrigationStatus: 'Irrigation Status',
    notWatering: 'Not watering',
    wateringActive: 'Watering active',
    lastWatered: 'Last watered: 2 hours ago',
    rainExpected: 'Rain Expected',
    rainExpectedDesc: 'Watering skipped — rain expected soon.',
    fieldSensors: 'Field Sensors',
    soilMoisture: 'Soil Moisture',
    temperature: 'Temperature',
    optimal: 'Optimal',
    humidity: 'Humidity',
    leafCheckTitle: 'Leaf Check',
    leafCheckDesc: 'Take a clear, close-up photo of a leaf to check for diseases.',
    takeOrUpload: 'Take or Upload Photo',
    checkingLeaf: 'Checking your leaf...',
    checkResult: 'Check Result',
    imageAnalysisComplete: 'Image analysis complete.',
    diagnosis: 'Diagnosis',
    earlyBlight: 'Early Blight',
    actionRequired: 'Action Required',
    confidenceLevel: 'Confidence Level',
    highConfidence: 'High Confidence',
    analyzedImage: 'Analyzed Image',
    advisoryTreatment: 'Advisory & Treatment',
    retakePhoto: 'Retake Photo',
    today: 'Today',
    yesterday: 'Yesterday',
    filter: 'Filter',
    all: 'All',
    irrigation: 'Irrigation',
    diseaseChecks: 'Disease Checks',
    alerts: 'Alerts',
    operations: 'Operations',
    speak: 'Speak...',
    voiceAssistant: 'Harvex Voice Assistant',
    askQuestion: 'Ask any farming or crop question...',
    samplePhotos: 'Sample Leaves for Diagnosis',
    cameraCapture: 'Open Camera',
    stopCamera: 'Close Camera',
    capture: 'Capture Frame',
    manualUpload: 'Upload Leaf Image',
    startWatering: 'Start Pump',
    stopWatering: 'Stop Pump',
    weatherForecast: 'Farm Weather',
    chat: 'Chat',
    settings: 'Settings',
    farmProfile: 'Farm Profile',
    saveProfile: 'Save Profile',
    cropRecommendations: 'Seasonal Crop Recommendations',
    recommendedCropsDesc: 'Optimal crops tailored to your soil, geography, and current season.',
    expectedYield: 'Expected Yield',
    idealWater: 'Ideal Water Needs',
    whySuitable: 'Suitability Reason',
    voiceCall: 'Hands-Free Voice Call',
  },
  hi: {
    appName: 'Harvex',
    dashboard: 'डैशबोर्ड',
    leafCheck: 'पत्ती की जाँच',
    history: 'इतिहास',
    cropHealth: 'फ़सल का स्वास्थ्य',
    healthy: 'स्वस्थ',
    allVitalsNominal: 'सभी महत्वपूर्ण अंग सामान्य हैं',
    irrigationStatus: 'सिंचाई की स्थिति',
    notWatering: 'सिंचाई नहीं हो रही',
    wateringActive: 'सिंचाई चालू है',
    lastWatered: 'आखिरी सिंचाई: 2 घंटे पहले',
    rainExpected: 'बारिश की उम्मीद',
    rainExpectedDesc: 'सिंचाई छोड़ दी गई — जल्द ही बारिश की उम्मीद है।',
    fieldSensors: 'फ़ील्ड सेंसर',
    soilMoisture: 'मिट्टी की नमी',
    temperature: 'तापमान',
    optimal: 'अनुकूल',
    humidity: 'नमी',
    leafCheckTitle: 'पत्ती की जाँच',
    leafCheckDesc: 'रोगों की जाँच के लिए पत्ती की स्पष्ट, नज़दीकी तस्वीर लें।',
    takeOrUpload: 'फ़ोटो लें या अपलोड करें',
    checkingLeaf: 'पत्ती की जाँच हो रही है...',
    checkResult: 'जाँच का परिणाम',
    imageAnalysisComplete: 'Image analysis complete.',
    diagnosis: 'रोग की पहचान',
    earlyBlight: 'अर्ली ब्लाइट (अगेती झुलसा)',
    actionRequired: 'कार्रवाई आवश्यक',
    confidenceLevel: 'Confidence Level',
    highConfidence: 'High Confidence',
    analyzedImage: 'Analyzed Image',
    advisoryTreatment: 'सलाह और उपचार',
    retakePhoto: 'फिर से फोटो लें',
    today: 'आज',
    yesterday: 'कल',
    filter: 'फ़िल्टर',
    all: 'सभी',
    irrigation: 'सिंचाई',
    diseaseChecks: 'रोग जाँच',
    alerts: 'चेतावनी',
    operations: 'कृषि कार्य',
    speak: 'बोलो...',
    voiceAssistant: 'हार्वेक्स वॉयस सहायक',
    askQuestion: 'फ़सल या मौसम से जुड़ा कोई सवाल पूछें...',
    samplePhotos: 'जाँच हेतु नमूना पत्तियाँ',
    cameraCapture: 'कैमरा खोलें',
    stopCamera: 'कैमरा बंद करें',
    capture: 'फ़ोटो खींचें',
    manualUpload: 'फ़ाइल चुनें',
    startWatering: 'पंप चालू करें',
    stopWatering: 'पंप बंद करें',
    weatherForecast: 'खेत का मौसम',
    chat: 'चैट',
    settings: 'सेटिंग्स',
    farmProfile: 'खेत का विवरण',
    saveProfile: 'विवरण सहेजें',
    cropRecommendations: 'मौसमी फसल अनुशंसा',
    recommendedCropsDesc: 'आपकी मिट्टी, क्षेत्र और मौसम के अनुसार सर्वोत्तम फसलें।',
    expectedYield: 'अनुमानित उपज',
    idealWater: 'जल आवश्यकता',
    whySuitable: 'अनुकूलता का कारण',
    voiceCall: 'हैंड्स-फ्री वॉयस कॉल',
  },
};

export const INDIAN_STATES_DISTRICTS: Record<string, string[]> = {
  'Maharashtra': ['Pune', 'Nashik', 'Nagpur', 'Ahmednagar', 'Solapur', 'Kolhapur', 'Chhatrapati Sambhajinagar', 'Jalgaon', 'Amravati', 'Satara', 'Sangli'],
  'Uttar Pradesh': ['Varanasi', 'Lucknow', 'Kanpur', 'Prayagraj', 'Agra', 'Meerut', 'Bareilly', 'Aligarh', 'Gorakhpur', 'Jhansi', 'Ayodhya'],
  'Punjab': ['Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala', 'Bathinda', 'Hoshiarpur', 'Firozpur', 'Sangrur', 'Moga'],
  'Haryana': ['Karnal', 'Hisar', 'Rohtak', 'Ambala', 'Sirsa', 'Kurukshetra', 'Sonipat', 'Panipat', 'Fatehabad'],
  'Madhya Pradesh': ['Indore', 'Bhopal', 'Jabalpur', 'Ujjain', 'Gwalior', 'Sagar', 'Dewas', 'Khargone', 'Ratlam', 'Vidisha'],
  'Gujarat': ['Ahmedabad', 'Surat', 'Rajkot', 'Vadodara', 'Bhavnagar', 'Junagadh', 'Anand', 'Mehsana', 'Kutch', 'Amreli'],
  'Rajasthan': ['Jaipur', 'Jodhpur', 'Kota', 'Bikaner', 'Ajmer', 'Udaipur', 'Sikar', 'Sri Ganganagar', 'Alwar', 'Barmer'],
  'Karnataka': ['Bengaluru', 'Belagavi', 'Mysuru', 'Hubballi-Dharwad', 'Shivamogga', 'Vijayapura', 'Davanagere', 'Kalaburagi', 'Mandya'],
  'Andhra Pradesh': ['Guntur', 'Krishna', 'East Godavari', 'West Godavari', 'Kurnool', 'Visakhapatnam', 'Anantapur', 'Chittoor'],
  'Telangana': ['Hyderabad', 'Warangal', 'Karimnagar', 'Nizamabad', 'Khammam', 'Nalgonda', 'Mahabubnagar'],
  'Tamil Nadu': ['Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem', 'Thanjavur', 'Erode', 'Tirunelveli', 'Dindigul'],
  'Bihar': ['Patna', 'Muzaffarpur', 'Gaya', 'Bhagalpur', 'Darbhanga', 'Purnia', 'Samastipur', 'Rohtas'],
  'West Bengal': ['Bardhaman', 'Murshidabad', 'Nadia', 'Hooghly', 'Malda', 'North 24 Parganas', 'Bankura'],
};

export const SOIL_TYPES = [
  { value: 'Black Soil (Regur)', labelEn: 'Black Soil (Regur)', labelHi: 'काली मिट्टी (रेगुर)' },
  { value: 'Alluvial Loam', labelEn: 'Alluvial Loam', labelHi: 'जलोढ़ दोमट मिट्टी' },
  { value: 'Red & Yellow Soil', labelEn: 'Red & Yellow Soil', labelHi: 'लाल और पीली मिट्टी' },
  { value: 'Laterite Soil', labelEn: 'Laterite Soil', labelHi: 'लेटराइट मिट्टी' },
  { value: 'Sandy / Arid Soil', labelEn: 'Sandy / Arid Soil', labelHi: 'बलुई / रेतीली मिट्टी' },
  { value: 'Clayey Loam', labelEn: 'Clayey Loam', labelHi: 'चिकनी दोमट मिट्टी' },
];

export const IRRIGATION_TYPES = [
  { value: 'Drip Irrigation', labelEn: 'Drip (Micro) Irrigation', labelHi: 'ड्रिप (टपक) सिंचाई' },
  { value: 'Sprinkler System', labelEn: 'Sprinkler System', labelHi: 'स्प्रिंकलर (फव्वारा) सिंचाई' },
  { value: 'Flood / Furrow', labelEn: 'Flood / Furrow Irrigation', labelHi: 'सतही / क्यारी सिंचाई' },
  { value: 'Rainfed (No Irrigation)', labelEn: 'Rainfed (No Irrigation)', labelHi: 'वर्षा आधारित (असिंचित)' },
];

